# Generated by Django 4.2 on 2023-04-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='PhotoFieldName',
            new_name='PhotoFileName',
        ),
    ]
