# Generated by Django 4.2 on 2023-04-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_photofieldname_employees_photofilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='IdDateOfJoining',
            new_name='DateofJoining',
        ),
    ]
