# Generated by Django 4.2 on 2023-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_rename_dateofjoining_employees_dateofjoining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateofJoining',
            new_name='IdDateofJoining',
        ),
    ]
