# Generated by Django 4.2 on 2023-04-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_rename_dateofjoining_employees_iddateofjoining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='IdDateofJoining',
            new_name='DateOfJoining',
        ),
    ]
